version: '3.3'
services:
  database:
    image: "mysql:5.7"
    container_name: db
    environment:
      - MYSQL_DATABASE=lportal
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_USER=user
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql

  liferay:
    image: liferay/portal:7.3.5-ga6
    image: liferay/portal:7.2.1-ga2
    container_name: lr
    environment:
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=passw0rd
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://db/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=user
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_UPGRADE_PERIOD_DATABASE_PERIOD_AUTO_PERIOD_RUN=true
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:11311:11311"
    volumes:
      - type: volume
        source: liferay-data
        target: /opt/liferay/data
      - ./build/docker/deploy:/opt/liferay/deploy
    depends_on:
      - database

volumes:
  liferay-data:
  database-data:
